### DISCUSSION TITLE
Anbindung 5573-0001

### DISCUSSION THREAD

**Discussion by eporsche** [Tom-Bom-badil/samson_trovis_557x#14] [General (de/en)]
Ich möchte gerne eine TTL Verbindung zu meinem Trovis 5573-0001 v2.02 herstellen.
Dazu habe ich einen ESP32 wie folgt angeschlossen:

ESP32 (Pin 16) -> RX -> Trovis (Pin 1)
ESP32 (Pin 17) -> TX -> Trovis (Pin 8)
ESP32 (Pin GND) -> GND -> Trovis (Pin 7)

--> keine weiteren Pin-Belegungen
--> der ESP hat eine eigene Versorgungsspannung

Trovis Konfiguration
CO6 --> F01 1 (Modbus aktiv)
CO6 --> F03 1 (Modem aktiviert)
CO6 --> F04 0 (Automatische Modemkonfiguration deaktiviert)
PA6 --> ST.-NR. 10 (Stationsadresse)
Die Baud-Einstellung habe ich nicht im Trovis gefunden

Kabellänge 
< 50cm

Debug zeigt folgendes:
[13:14:30][D][modbus_controller:040]: Modbus command to device=10 register=0x10 countdown=0 no response received - removed from send queue
[13:14:30][D][uart_debug:114]: >>> 0A:03:00:16:00:01:64:B5
[13:14:31][D][uart_debug:114]: >>> 0A:03:00:16:00:01:64:B5
[13:14:31][D][uart_debug:114]: >>> 0A:03:00:16:00:01:64:B5
[13:14:31][D][uart_debug:114]: >>> 0A:03:00:16:00:01:64:B5
[13:14:31][D][uart_debug:114]: >>> 0A:03:00:16:00:01:64:B5

CRC Fehler werden keine angezeigt

Folgende yaml Einstellungen habe ich vorgenommen:

```yaml 

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

[..WiFi einstellungen..]

time:
  platform: sntp

uart:
  id: mod_bus
  rx_pin: 16
  tx_pin: 17
  baud_rate: 19200
  debug:

modbus:
  id: modbus1
  uart_id: mod_bus

modbus_controller:
  - id: trovis
    address: 10
    modbus_id: modbus1
    setup_priority: -10

sensor:
  - platform: modbus_controller
    modbus_controller_id: trovis
    name: "Außentemperatur"
    id: AussentempAF1
    unit_of_measurement: "°C"
    icon: "mdi:home-thermometer"
    register_type: holding
    address: 9
    accuracy_decimals: 1
    filters:
      multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: trovis
    name: "Vorlaufsollwert"
    id: VorlSollwRk1
    unit_of_measurement: "°C"
    register_type: holding
    address: 999
    accuracy_decimals: 1
    filters:
      multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: trovis
    name: "Vorlauftemperatur"
    id: VorlauftempVF1
    unit_of_measurement: "°C"
    register_type: holding
    address: 12
    accuracy_decimals: 1
    filters:
      multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: trovis
    name: "Rücklauftemperatur"
    id: RueckltempRueF1
    unit_of_measurement: "°C"
    register_type: holding
    address: 16
    accuracy_decimals: 1
    filters:
      multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: trovis
    name: "Wassertemperatur"
    id: SpeichertempSF1
    unit_of_measurement: "°C"
    register_type: holding
    address: 22
    accuracy_decimals: 1
    filters:
      multiply: 0.1
```
Leider füllen sich die Werte der Sensoren nicht und mir fehlen die Ideen was hier noch das Problem sein könnte. Vielleicht, weiß hier jemand weiter?
