### DISCUSSION TITLE
HA "Advanced Trovis Visu" - aktueller Stand

### DISCUSSION THREAD

**Discussion by Tom-Bom-badil** [Tom-Bom-badil/samson_trovis_557x#44] [General (EN/DE)]
Fortgesetzt von [hier](https://github.com/Tom-Bom-badil/samson_trovis_557x/discussions/27#discussioncomment-10933080).

> @falkio8 wrote on Oct 14, 2024:

Hi @Tom-Bom-badil, das sieht ja schon richtig gut aus. Hatte letzte Woche keine Zeit um hier weiter zu machen.
Ich kümmere mich jetzt erstmal um das Grid.

1. das Sensor Template ist hier noch nicht abgelegt oder?
2. Schritt 3 für mich wäre dann die VL Kurve darzustellen, hierzu hast du bisher auch noch keine neue Vorlage hochlgeladen oder? Das aktuelle Snippet enthält noch die VL Berechnung in der der card.
3. Ich kapiere leider nicht wie ich in dem community Bereich Dateien von mir hochladen kann, würde gerne meine Bilder und snippets teilen weiß aber nicht wie.

Danke, falkio

**Comment by Tom-Bom-badil** [comment]
Hallo @falkio,

die Dateien hier auf Git und mein aktueller Entwicklungsstand sind tatsächlich so ca. 2-3 Wochen auseinander. Das nächste Update kommt in Kürze (vermutlich im Laufe dieser Woche - sobald ich wieder einen einigermaßen vorzeigbaren Stand habe, der Einsteigern in die Materie nach einem copy&paste nicht sofort auf die Füße fällt).

Ziel ist immer noch eine vollständige Visu, die mit nur wenigen Anpassungen sofort lauffähig sein soll (kurz configuration.yaml anpassen, 2 Verzeichnisse reinkopieren, ein paar wenige Template Sensors anpassen, läuft). Im zweiten Ausbauschritt soll neben der reinen Visualisierung auf einer Unterseite auch das Rückschreiben von Werten (Heizkurve usw) über eine Unterseite möglich sein. Im dritten Schritt will ich die (Langzeit)Daten statt in HA-SQLite auf meinem sowieso laufenden MariaDB Server ablegen.

Hier nochmal zur Erinnerung meine aktuelle Visu (SmartHomeNG, Smartvisu), die bei mir seit vielen Jahren unverändert läuft. Sie dient als Basis für die zukünftige HA Visu:

![image](https://github.com/user-attachments/assets/db94f36e-ab1a-416b-87bb-f2e9c8e1183e)

Muster, wie die configuration.yaml dann später ungefähr aussieht (alles zur Trovis wird aus den Haupt-YAML-Dateien ausgekoppelt, daher ist einfaches copy-paste möglich):
```yaml
modbus:
  - name: trovis
    type: !secret trovis_connection_type
    host: !secret trovis_ip
    port: !secret trovis_port
    sensors:        !include_dir_merge_list trovis557x/sensors/
    binary_sensors: !include_dir_merge_list trovis557x/binary_sensors/
    switches:       !include_dir_merge_list trovis557x/switches/
    climates:       !include_dir_merge_list trovis557x/climates/

sensor trovis:      !include trovis557x/template_sensors.yaml
sensor trovis_stat: !include trovis557x/statistics.yaml
```

Aktueller Entwicklungsstand:

![aktuell1](https://github.com/user-attachments/assets/3332259e-3a8f-4fcb-ab37-7b914393b374)

Zukünftige HA-Plots mit Plotly (aus einer meiner 'Spielseiten', noch in 'schick' in die Hauptseite zu integrieren - zur Zeit kommen die angezeigten Werte aus Altdaten von smartHomeNG):

![plots](https://github.com/user-attachments/assets/6462b18d-3fe8-4791-820b-7037a1fd6ef5)

Video mit aktuellem Verhalten der linken Seite (neu sind per Template Sensor _frei einstellbare_ (!) single- und double klicks auf den Reglerbuttons; an der Darstellung für Hk4 (double click auf dem 3. Button) sitze ich gerade:

https://github.com/user-attachments/assets/7a08b16d-aafe-49f3-a58c-7a3887b85fac

Muster, wie man später die Bilder links oben oben konfiguriert (gesamtstatus-0.svg ... gesamtstatus-9.svg werden durch Eingabe einer einfachen Zahl automatisch angeholt):
```yaml
      trovis_regler_gesamtstatus:
        unique_id: trovis_r_gesamtstatus
        friendly_name: "Trovis Regler Gesamtstatus"
        value_template: >-
          {% set hk1 = is_state('binary_sensor.trovis_hk1_umwaelzpumpe', 'on') %}
          {% set ww  = is_state('binary_sensor.trovis_hk4_speicherladepumpe', 'on') %}
          {% if hk1 and not ww %} 1
          {% elif ww and not hk1 %} 2
          {% elif hk1 and ww %} 3
          {% else %} 0
          {% endif %}
```

Muster, wie man die Buttonclicks / double-clicks dann auf das gewünschte Verhalten einstellt (bei mir: Button 1 click/double-click=Hk1, Button 2 click/double-click=Hk2, Button 3 click = Hk3, Button 3 double click = WW):
```yaml
      # Trovis - heating curve to display if you tap/click a button
      # set to 0/1/2/3/4 (0=do nothing, 1..3=Rk1..3/Heating, 4=Rk4/HotWaterTank)

      trovis_regler_button1_click: # top button
        unique_id: trovis_r_button_1_click
        friendly_name: "Trovis Regler Button1 Klick/Tap"
        value_template: 1

      trovis_regler_button1_doubleclick:
        unique_id: trovis_r_button_1_doubleclick
        friendly_name: "Trovis Regler Button1 Double Klick/Tap"
        value_template: 1

      trovis_regler_button2_click: # middle button
        unique_id: trovis_r_button_2_click
        friendly_name: "Trovis Regler Button2 Klick/Tap"
        value_template: 2

      trovis_regler_button2_doubleclick:
        unique_id: trovis_r_button_2_doubleclick
        friendly_name: "Trovis Regler Button2 Double Klick/Tap"
        value_template: 2

      trovis_regler_button3_click: # bottom button
        unique_id: trovis_r_button_3_click
        friendly_name: "Trovis Regler Button3 Klick/Tap"
        value_template: 3

      trovis_regler_button3_doubleclick:
        unique_id: trovis_r_button_3_doubleclick
        friendly_name: "Trovis Regler Button3 Double Klick/Tap"
        value_template: 4
```

Es gab kürzlich einige unerwartete Hürden zu umschiffen (Picture entity card kann zB keine Templates --> Buttons mussten anders als geplant implementiert werden, Plotly hat einen Anzeige-/Refresh Bug --> musste die JS-Heizkurvenberechnung innerhalb von Plotly entfernen und in Template Sensors packen usw usw). Daher dauert alles im Moment leider etwas länger als geplant.

Soweit erstmal das Update und eine kurze Roadmap,

/tom

_p.s. Zu Deiner Frage in Sachen Github/Community Uploads: Zu lang, um es hier aufzuschreiben, bitte mal googlen. Du müsstest einen eigenen Fork dieses Gits erstellen, dort pflegst Du (idealerweise in einer neuen Branch) Deine Änderungen ein, und 'pushed' diese dann per Pull Request an dieses Repo zurück._

**Reply by falkio8** [reply]
Guten Morgen @Tom-Bom-badil 

danke schon mal. Das mit dem Fork versuche ich mal rauszufinden.
Für mich der nächste Schritt wäre die Darstellung der VL Kurve inkl. Berechnung über das Template aber wie gesagt hier warte ich auf deine Snippets. Das mit den Buttons werde ich erstmal nicht implementieren. Der Rest ist ja bereits umgesetzt und funktioniert ganz gut. Mein aktueller Stand:

![grafik](https://github.com/user-attachments/assets/a3092662-e180-4554-9f85-ea3ad290ad0b)

**Reply by Tom-Bom-badil** [reply]
Hier schon mal vorab die Heizkurve, damit Du weitermachen kannst (Hk2 und Hk3 analog zu Hk1). Die Kurve wird als Liste in Attributen und nicht im Sensor selbst gespeichert, denn der Wert/Inhalt eines Sensors ist im Gegensatz zu Attributen auf 256 Bytes begrenzt (das reicht nur für 1 Nachkommastelle, und dann bekommt die Heizkurve "Ecken" - wieder einevon den Klippen, die ich kürzlich umschiffen musste):

``` yaml
# Trovis - Heating curves HK123
# moved here from 'sensors' due to 256 Bytes length limitation (arrays too long)
trovis_hk123_heizkurven:
  unique_id: trovis_hk123_heizkurven
  friendly_name: "Trovis Hk123 Heizkurven"
  value_template: "siehe Attribute"
  attribute_templates:

    x_werte: >-
      {% set x = namespace(valsx='') %}
      {% for lauf in range(-20,21) %}
        {% set x.valsx = x.valsx + lauf|string + ',' %}
      {% endfor %}
      {{ x.valsx[:-1].split(',') | map('int') | list }}

    hk1: >-
      {% set tagbetrieb = is_state('binary_sensor.trovis_hk1_tagbetrieb', 'on')| int %}
      {% set tagsoll = states['sensor.trovis_hk1_raumsoll_tag'].state|float %}
      {% set nachtsoll = states['sensor.trovis_hk1_raumsoll_nacht'].state|float %}
      {% set niveau = states['sensor.trovis_hk1_niveau'].state|float %}
      {% set steigung = states['sensor.trovis_hk1_steigung'].state|float %}
      {% set vl_min = states['sensor.trovis_hk1_vl_min'].state|float %}
      {% set vl_max = states['sensor.trovis_hk1_vl_max'].state|float %}
      {% set y = namespace(valsy='') %}
      {% if tagbetrieb %}
        {% set soll = tagsoll | int %}
      {% else %}
        {% set soll = nachtsoll | int %}
      {% endif %}
      {% for lauf in this.attributes.x_werte %}
        {% set vl = (24 + niveau + 2*steigung*(soll-20) - (0.1 + 0.9*steigung) *
                    (1.5*(lauf-20) + 0.01*((lauf-20)*(lauf-20)))) %}
        {% if vl < vl_min %}
          {% set vl = vl_min %}
        {% elif vl > vl_max %}
          {% set vl = vl_max %}
        {% endif %}
        {% set y.valsy = y.valsy + vl|round(2)|string + ',' %}
      {% endfor %}
      {{ y.valsy[:-1].split(',') | map('float') | list }}
```

Viel Erfolg!

/tom

**Reply by falkio8** [reply]
Guten Morgen @Tom-Bom-badil 

vielen Dank. Ich hatte dein Berechnungstemplate bereits abgetippt und in die Templates gepackt. Das mit der Sensor limitation wusste ich nicht. Allerdings habe ich es eh nicht geschafft die x und y Werte an ein Plotly zu übergeben :-(

Woran ich gerade komplett scheitere und verzweifele ist ein Plotly überlagert auf meinem Trovis svg anzuzeigen. Das klappt überhaupt nicht so wie ich das will.
![grafik](https://github.com/user-attachments/assets/0e41629c-5cd9-457d-aa73-d4aeeb49b409)
Ich habe es mit picture-elements probiert das auch in Verbindung mit einem grid oder stacks. Dann habe ich noch custom:layout-card mit custom:grid-layout und custom:mod-card aber nichts zeigt mir die elemente oberhalb von einem svg an der richtigen position in der richtigen größe an.

Wenn ich das richtig sehe hast du dir innerhalb deines dashboard stacks nur ein grid aufgebaut ohne Bild im Hintergrund. Passt bei mir leider nicht so richtig weil ich ja ein Bild von der Anlage habe.

**Reply by Tom-Bom-badil** [reply]
Guten Morgen @falkio8,

HA ist in Bezug auf die Visu-Programmierung ziemlich eigen. Wer aus anderen Systemen gewohnt ist, Dinge mal eben schnell nachträglich einzubauen und dann per css geradezuziehen, fällt zumeist auf die Nase.

Deinen Ansatz, ein svg als Hintergrundbild zu nehmen und dann mit Elementen zu füllen, hatte ich am Anfang auch ausprobiert, ihn dann aber verworfen. Funktionieren sollte es aber trotzdem, wenn man wie folgt vorgeht:

- Als 'Hauptbild' ein transparentes Bild nehmen,
- dann das tatsächliche Hintergrundbild als erstes Element `type: image` einbinden,
- kurze Texte in Elemente `type: state-label` packen,
- längere gehen über einen vorher vorbereiteten Template Sensor in Elemente `type: custom:button-card` (dort geht dann auch css),
- Plots wandern in Elemente `type: custom:plotly-card`.

Jedes Element lässt sich dann beliebig positionieren - wenn die normalen styles: nicht reichen, bei Bedarf mit card-mod nachhelfen, in schwierigen Fällen `!important` nehmen:
```yaml
type: custom:plotly-graph
name: heizkurve
card_mod:
  style: |
    ha-card { 
      --ha-card-border-radius: 0px; 
      --ha-card-border-color: #990000;
      --ha-card-border-width: 2px;
      --card-mod-icon-color: white;
      width: 100% !important;
      height: 20vh;
      margin-left: 1vw;
      ...
    }
```

Genau auf diese Art entsteht zB gerade meine WW-Statusanzeige rechts unten (ist derzeit noch im Rohformat):

![image](https://github.com/user-attachments/assets/051b996b-b947-4f29-9dfa-fac5cadd14af)

Beim Festlegen von Größen und Positionen und dem Verständnis, welches Element wem untergeordnet ist, helfen die Entwicklertools ungemein (rechte Maustaste --> untersuchen bzw. F12). Damit kann man ggf Elemente auch mal durch die Gegend 'schieben', um die richtigen Werte zu finden.

Viel Erfolg!

/tom

**Reply by falkio8** [reply]
Danke @Tom-Bom-badil 

ich habe es jetzt bei picture-element belassen und dann das plotly als element eingebunden mit der mod card. Wenn ich nur image -> transparent mache und dann ein image als element nehme füllt es nicht die gesamte card aus.

Jetzt habe ich aber das Problem, dass das plotly nicht an seiner relativen position bleibt sondern sich verschiebt wenn sich die Dashboard Größe verändert, der Text links bleibt merkwürdigerweise an seinem Platz. Die Angaben sind aber eigentlich relativ (%, vh und vw):

                      - type: custom:plotly-graph
                        name: ''
                        styles:
                          card:
                            - background-color: transparent
                            - top: 0%
                            - left: 0%
                        card_mod:
                          style: |
                            ha-card { 
                              --ha-card-border-radius: 0px; 
                              --ha-card-border-color: #990000;
                              --ha-card-border-width: 2px;
                              --card-mod-icon-color: white;
                              width: 42% !important;
                              height: 35vh;
                              margin-left: 42vw;
                              margin-top: -26vw;
                            }  

![grafik](https://github.com/user-attachments/assets/1657c140-11d4-48a3-8eef-ebc48caf8412)
![grafik](https://github.com/user-attachments/assets/b2307720-434c-41aa-b426-095819d4837d)

Und dann noch ne Frage zu dem Template oben, das kommt so wie es ist in die Template.yaml? Dann schmeisse ich den String Sensor aus den templates raus. Und du müsstest mir noch verraten wie ich die x und y Werte an das plotly übergebe.

Danke!

**Comment by Tom-Bom-badil** [comment]
Zur Position/Größe: Statt mit festen Werten für vh/vw kannst Du das Element auch mit `transform: translate(x%, y%)` über den Style positionieren, wie in der [Doku](https://www.home-assistant.io/dashboards/picture-elements/) beschrieben. Ildar Gabdullin hat dazu [hier](https://community.home-assistant.io/t/styling-elements-in-picture-elements-card-a-small-tutorial/315252) vor einiger Zeit ein absolut geniales Tutorial geschrieben.

Die Datei für das Heizkurve-Template ist die [template-sensors.yaml](https://github.com/Tom-Bom-badil/samson_trovis_557x/blob/master/HomeAssistant/trovis557x/template_sensors.yaml).

Zur Übergabe der Werte sowas in der Art hier in Plotly als Entity definieren (Achtung, ungetestet, müsste aber passen - bei mir ist das wegen der Heizkreis-Umschaltung deutlich mehr Code und läuft noch über weitere Variablen):
```yaml
- entity: ''
  name: Heizkurve
  line:
    shape: spline
    color: black
  x: |-
    [[[
      return states['sensor.trovis_hk123_heizkurven'].attributes.x_werte;
    ]]]
  'y': |-
    [[[
      return states['sensor.trovis_hk123_heizkurven'].attributes.hk1;
    ]]]
```

Tada:
![image](https://github.com/user-attachments/assets/6a0d9aa2-3dd0-474a-a871-6db16966777b)

Viel Erfolg!

/tom
