### DISCUSSION TITLE
HA-Struktur, Einstieg und Roadmap?

### DISCUSSION THREAD

**Discussion by sibbl** [Tom-Bom-badil/samson_trovis_557x#55] [General (EN/DE)]
Hallo zusammen,

ich bin in den letzten Tagen frisch auf das Projekt aufmerksam geworden, da ich seit einiger Zeit die Trovis 5578e in HA integrieren wollte und nun endlich dafür mal Zeit war.

Aus dem Grund habe ich seit letztem Jahr schon einige Sensoren und Switches geschrieben gehabt, die für wenige spezifische Use Cases ausreichend waren, bevor ich den sehr umfangreichen Code hier gefunden habe. Erst einmal ein großer Dank für all diese Arbeit!

Daraus ergaben sich einige Fragen:

1. ist ein Schreiben in Holdings geplant? Ich hatte konkret die Zirkulationspumpe als Switch integriert, hier ist sie nur als Read-Only-Sensor implementiert.
2. was ist das empfohlene Set-Up? Im Wiki fand ich rein gar nichts zur HA-Integration, in einigen Ordnern sind Readmes und auf z.B. die Dashboard-Snippets sind teilweise ganze Tabs, Panels, ... ohne konkrete Dokumentation wozu diese gut sind. Einen konkreten Einstieg vermisse ich aktuell. Ist so etwas geplant und wie kann man dabei helfen?
3. Die YAML-Konfiguration lässt sich momentan out of the box nicht ausführen:
```yaml
homeassistant:
  packages:
    trovis:
      input_number:      !include trovis557x/input_numbers.yaml
      input_datetime:    !include trovis557x/input_datetime.yaml
      sensor main:       !include trovis557x/template_sensors.yaml
      sensor statistics: !include trovis557x/statistics.yaml
      sensor curves:     !include trovis557x/heating_curves.yaml
      template triggers: !include trovis557x/trigger_actions.yaml
      automation start:  !include trovis557x/trigger_startup.yaml
      automation update: !include trovis557x/trigger_updates.yaml
```

ist invalides YAML. Keys können auf diese Art keine Leerzeichen enthalten und als Keys innerhalb des "trovis"-Objekts sind meines Wissens nach nur die von HA unterstützen Werte erlaubt (d.h. 1x "sensor" und nicht "sensor main", "sensor statistics", ...). Funktioniert die aktuelle Konfig für irgendjemanden oder ging das früher mal, weshalb es so ist?

Ich würde sonst gern einen PR anbieten, der es folgendermaßen umstrukturiert und die sensor-, template- und automation-Dateien in die entsprechenden Unterordner einsortiert:

```yaml
homeassistant:
  packages:
    trovis:
      input_number:      !include trovis557x/input_numbers.yaml
      input_datetime:    !include trovis557x/input_datetime.yaml
      sensor:            !include_dir_merge_list trovis557x/sensors/
      automation:        !include_dir_merge_list trovis557x/automations/
      templates:         !include_dir_merge_list trovis557x/templates/
```

Alles in allem würde ich mich sehr über eine grobe Roadmap oder allgemeine offene Punkte freuen, an denen man die Zusammenarbeit koordinieren könnte.  Bei manchen Aussagen in Diskussionen von z.B. Februar weiß ich nicht, inwiefern diese schon überholt sind oder noch Input gefragt ist. Langfristig könnte ich mir auch eine über HACS verteilbare custom_component vorstellen, womit ich bereits Erfahrung habe.

Danke im Voraus und allen mitlesenden einen entspannten Jahresausklang!
