### DISCUSSION TITLE
Einstellen der Betriebsart RK1 über Modbus nicht möglich

### DISCUSSION THREAD

**Discussion by THorst92** [Tom-Bom-badil/samson_trovis_557x#8] [General (de/en)]
Hallo,

evtl. kann mir jemand helfen. Ich lese und steuere mein TROVIS 5573-1004, FW 2.60 mit ESPHome. Soweit funktionieren die meisten Dinge. Lesen kann ich alle relevanten Daten. Beim schreiben habe ich bei den meisten Registern auch keine Probleme, z.B.:
- Register 111 (BetriebsArtTW)
- Register 1002 (TagSollRk1)
- Register 1005 (SteigHeizKLRk1)

Nur bei einem Register habe ich Probleme:
- Register 105 (BetriebsArtRk1)

Wenn ich einen Wert setzte (1, 2, 4, 5) wird dieser nicht übernommen.

Register 144 (WriteEnModem) habe ich korrekt gesetzt (GLT Icon wird im Display angezeigt).

Hatte jemand bereits so ein Fehler und kann mir helfen?

**Comment by Tom-Bom-badil** [comment]
Da war doch mal was ... hab's nach kurzer Suche [hier](https://knx-user-forum.de/forum/öffentlicher-bereich/knx-eib-forum/1815748-heizungsregler-samson-trovis-557x-an-knx-gateway-mit-openknx?p=1831554#post1831554) gefunden:

Zitat:
"Zu den Betriebsarten-Einstellungen...
Ich habe festgestellt **_das die Betriebsart etwas Zeit braucht um nach Änderung über MB beim Auslesen auch so angezeigt zu werden_**. ....why ever
Du hast Deinen Regler ja schon produktiv am Netz, kannst also nach Eingriff eine Veränderung sehen. Lies und /oder Sende doch mal mit den Register-Nummern für HK2. Ich würde fast denken damit wird der WW-Kreis geregelt....auch wenn HK3 angezeigt wird.
Ansich hat die 5573 eben nur 2 Heizkreise die sie ansteuern kann."

Also vielleicht hilft es schon, nur etwas zu warten ...

/tom

**Reply by THorst92** [reply]
Hallo,

danke dafür! Leider ändert sich da auch nichts, wenn ich lange warte. Aber ich habe ich der Diskussion gelesen, dass manche Themen auch mit dem GLT Modus zusammenhängen. Der ist aktuell aktiv. 
Das seltsame ist, dass ich die Betriebsart vom Trinkwasser ohne Probleme ändern kann (Auch im GLT-Modus). Und auch der aktuelle Status vom HK1 wird mir korrekt angezeigt. Wenn ich ihn ändere bekomme ich im nächsten Zyklus wieder den unveränderten (mit dem Display übereinstimmenden) Wert gemeldet.

Ich werde nochmal versuchen die Betriebsart des HK1 ohne GLT zu ändern, ob das etwas ändert.

Gruß, Thorsten

**Reply by Tom-Bom-badil** [reply]
In einer der Diskussionen hat jemand geschrieben, dass er bestimmte Schreibvorgänge grundsätzlich durch erneutes Schreiben der Kennzahl quittiert. Ich finde aber leider die Quelle dafür nicht mehr, es waren einfach zu viele Diskussionen in zu vielen verschiedenen Foren ...

/tom

**Reply by THorst92** [reply]
Das hat leider auch nicht geholfen. Habe auch die Steuerung neu gestartet und wollte es ohne GLT-Modus versuchen, aber der geht automatisch an (entweder, wenn ich lese oder schreibe).
Nun habe ich einen PC mit TROVIS-View dran gehängt. Auch hier konnte ich den Betriebsmodus non Rk1 nicht ändern. Die Umwälzpumpe des Hk1 konnte ich ein und ausschalten. Allerdings hat der Regler danach einen Neustart gemacht.

Gruß, Thorsten

**Reply by Tom-Bom-badil** [reply]
Dass TrovisView da auch nicht will, ist äußerst ungewöhnlich; das mit dem Neustart nach Start/Stop von UP1 auch.
Welche Anlage ist eingestellt? Hast Du mal versucht, Rk2 statt Rk1 zu nehmen (den Fall hatten wir schon mal auf ner 5573)?
/tom

Edit/Nachtrag: Zur Zeit fische ich auch noch im Trüben; aber zur Sicherheit - gemäß Samson sind bei der 5573 nur 2,4,5 gültige Werte für den HK1 (2=Stdby, 4=Sonne, 5=Mond); evtl auch mal probieren, vorher Coil 89 explizit auf GLT (=0) zu setzen.

**Reply by THorst92** [reply]
Als Anlage ist 2.1 eingestellt. Rk2 habe ich auch versucht allerdings das identisches Verhalten zu Rk1 beobachtet.
Zum Nachtrag: 
Ich denke du meinst ` 'EBNBetrArtRk1':     { 'ID':    88, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Ebene Betriebsart Rk1 (HR40106)' },`, oder?
Ich habe sowohl diesen, als auch den für Rk2 und TW zu meiner Konfig hinzugefügt. Diese gehen automatisch, sobald ich den Wert im Betriebsart-Register (105, 111) ändere, auf 0. Später gehen sie auch automatisch wieder auf 1. 
Wenn ich versuche sie über meinen ESP32 zu setzten, erhalte ich folgende Meldung:
```
[12:00:56][E][modbus_controller:091]: Modbus error function code: 0x5 exception: 1 
[12:00:56][E][modbus_controller:100]: Modbus error - last command: function code=0x5  register address = 0x58  registers count=1 payload size=2
```
Ich kann später nochmal versuchen diese über TROVIS-View zu setzen.
Den Wertebereich habe ich berücksichtigt.

Ich habe parallel mal an den Service von Samson geschrieben. Mal sehen ob da was zurück kommt.

**Reply by THorst92** [reply]
Nun klappt es. Ich weiß aber nicht genau warum. 
Auf anraten des Service von Samson habe ich C04 -> F06 (Pumpenparallellauf) auf 1 gestellt und die untergeordneten Parameter auf 0 min und 20°C. 
Danach konnte ich die Register 105 (BetriebsArtRk1) schreiben und die Betriebsart hat sich geändert.
Nachdem ich C04 -> F06 wieder auf 0 geändert hatte, war das Ändern der Betriebsart weiter möglich.

Also eine wirkliche Lösung habe ich nicht gefunden, aber nun geht es.

**Reply by Tom-Bom-badil** [reply]
Glückwunsch! Der Weg dahin dahin klingt irgendwie eigenartig - aber Hauptsache, es läuft. :)

**Reply by THorst92** [reply]
Sehe ich auch so 😅
Danke für die Hilfe!

**Reply by brix29** [reply]
Hi @THorst92,

ich versuche seit Tagen mein Trovis 5573-1 v. 2.63 an Home Assitant anzubinden, aber bekomme keine Antwort vom TROVIS.
(Problemlos klappt eine Verbindung mit einem FT232RL USB zu TTL Serial Adapter und Trovis View mit derselben Konfiguration.)

Ich nutze folgendes Setup: 

- TROVIS 5573-1
- Home Assistant mit ESPHome. 
- ESP32 (ESP-WROOM-32) mit einem TTL-zu-RS485-Modul
- Stromversorgung des ESP32 über USB

Das Problem:
Nur die TXD-Led vom RS485 blinkt, die RXD bleibt aus. Gleiches sehe ich im ESPHome-Logfile:

- [15:22:52][D][uart_debug:114]: >>> 0A:03:00:16:00:01:64:B5
- [15:22:52][D][modbus_controller:032]: Modbus command to device=10 register=0x16 countdown=0 no response received - removed from send queue

Kannst Du mir einen Tipp geben, woran es liegen könnte? 
- Welches Hardware-Setup nutzt Du? 
- Welchen Code hast Du im ESPHome yaml?
- Hast Du spezielle Einstellungen beim Trovis? (Ich nutze: Modbus an, Modem und Auto Config aus, Adresse 247 und 10 getestet)

Über jede Hilfe/Idee wäre ich sehr dankbar.

Viele Grüße!

**Reply by THorst92** [reply]
Hi @brixharlem,

mein HW-Setup findest du hier: [Link](https://github.com/Tom-Bom-badil/samson_trovis_557x/discussions/6#discussioncomment-7033177)
Du benötigst den TTL-zu-RS485-Converter gar nicht, sondern kannst die Buchse direkt an den ESP32 anschließen.
Das Ethernet-Kabel sollte, wie an verschiedener Stelle beschrieben, nicht zu lange sein.
Ein Step-Down-Converter in der Nähe der Buchse stört auch zu sehr. Die USB-Versorgung nutze ich aktuell auch.
Am TROVIS habe ich Modbus an und das Modem aus. Außerdem habe ich die Adresse 10 eingestellt, ich denke aber, dass es auch mit Adresse 247 gehen sollte, wenn du diese in der YAML-Config angibst.

Hier meine YAML (basierend auf [dieser](https://github.com/Tom-Bom-badil/samson_trovis_557x/discussions/6#discussioncomment-4368284)), ich habe sie eigentlich in Packages unterteilt und nun zusammenkopiert. Schau mal ob sie geht. Auch ist dort noch ein Wärmemengenzähler mit integriert basierend auf diesem [Repo](https://github.com/dgow/LandisGyrUH50_T555).

[trovis.txt](https://github.com/Tom-Bom-badil/samson_trovis_557x/files/13316241/trovis.txt)

Ich hoffe du bekommst es damit zum laufen.

Viele Grüße!

**Reply by brix29** [reply]
😅 Oh mann, viel zu kompliziert gedacht. Die ersten Werte kommen bei mir jetzt auch über ein 5m Kabel problemlos. 
Vielen Dank, @THorst92 für die schnelle Rückmeldung und den Anstoss! @Tom-Bom-badil Dir auch ganz besonderen Dank für das geniale Wiki!

**Reply by THorst92** [reply]
Perfekt! :)
Danke für den Hinweis, dass es auch über ein 5m Kabel geht!

**Reply by brix29** [reply]
Hi @THorst92,
läuft soweit alles fast perfekt. Seltsamerweise ist bei mir "Write Enable" (Register 144) auf 0 gesprungen. Ich bekomme es nicht hin in über Home Assitant wieder zu aktivieren. Auch in der Trovis direkt, habe ich es nicht hinbekommen. 

ESPHome Log:
```
[11:16:55][D][number:010]: 'Write Enable' - Setting
[11:16:55][D][number:029]:   Value: 1.000000
[11:16:55][D][modbus.number:055]: Updating register: connected Sensor=Write Enable start address=0x90 register count=1 new value=1.00 (val=1.00)
[11:16:55][D][modbus:105]: Modbus error function code: 0x86 exception: 6
[11:16:55][E][modbus_controller:068]: Modbus error function code: 0x6 exception: 6 
[11:16:55][E][modbus_controller:077]: Modbus error - last command: function code=0x6  register adddress = 0x90  registers count=1 payload size=2
```

Kannst Du mir da helfen?

Vielen Dank!

LG

**Reply by THorst92** [reply]
Hi @brixharlem,

wenn ich den Code auf den Standard-Code 1732 ändere wird der eigentlich angenommen. Er springt aber nach dem nächsten Auslesen direkt wieder auf 1 zurück.
Kommst du mit dem Code in die Einstellungen, wenn du ihn direkt am Gerät eingibst oder geht das gar nicht mehr?


Viele Grüße

**Reply by brix29** [reply]
Hi @THorst92,

Danke Dir. Ich dachte "Write Enable" wird gebraucht, damit alle Einstellungen über HA verändert werden können. Es funktioniert alles perfekt - unabhängig von "Write Enable".
Nutzt Du "Automations" für die Steuerung? Regelung über Anwesenheitssensoren oder ähnliches? Wetter-Vorherssagen? Sonneneinstrahlung? Möglichkeiten über Möglichkeiten. 😁
An welchen Werten regelst Du? Deine ursprüngliche Frage war ja zur Änderungs der Betriebsart. Prinzipiel könnte man ja alles über die Soll-Werte steuern oder spricht etwas dagegen?

VG

**Reply by THorst92** [reply]
Hi @brixharlem,
die Funktion von WriteEnable habe ich auch noch nicht ganz verstanden. Ich hab es bisher eigentlich nicht bewusst gebraucht bei meinen Tests.
Welche Sollwert meinst du genau? Zimmertemperatur oder Vorlauftemperatur.
Meine Zielfunktion ist folgende:
Die Heizung kann ich gesamthaft manuell Ein- und Ausschalten (dazu gehören auch die Thermostate). Da wir eine Einrohrheizung haben mit vier Strängen (pro Stockwerk) habe ich dort an dem Heizverteiler für jeden Heizkreis ein Ventil angebracht. Diese sollen (wenn ich die die Ansteuerplatine, die auch auf ESPHome basieren soll, fertiggestellt habe) automatisch auf und zugehen. Als Basis soll die Ventilöffnung der Thermostate dienen (HmIP ETRV[2] Ventile). D.h. wenn alle Ventile zu sind in einem Strang, wird auch der komplette Strang abgeschaltet, damit das Wasser dort nicht im Kreis gepumpt wird. Wenn alle Kreise zu sind, dann soll die Fernwärmestation auch in Standby gehen und nur noch das Brauchwasser heizen.
Daher lasse ich die Trovis vieles selbst regeln (Vorlauftemperatur abhäng von Außentemperatur, Umschaltung Heizung/Brauchwasser, etc…) und schalte nur den Heizkreis zwischen Auto und Standby.
Das ist allerdings alles noch Zukunft, da wie oben beschrieben die Platine noch nicht fertig ist. 😉 
Ob noch weitere Funktionen hinzukommen muss ich dann sehen wenn die Basis zuverlässig tut.
Umsetzen werde ich das alles in NodeRed, das in HomeAssistant integriert ist. Da finde ich die Automatisierung deutlich übersichtlicher. Kommt evtl. davon, dass ich beruflich SPS ähnliche Rechner programmiere 😉 
Sonneneinstrahlung wäre bei den Rollos interessant! Da muss ich mich auch mal dran setzen. Aber das ist hier Off-Topic 😉 
Was hast du vor?

Viele Grüße

**Reply by brix29** [reply]
Hi @THorst92, 

klingt nach einem großen Plan. 👍 Soweit bin ich leider noch nicht, dass ich mir regelbare Ventile in die Heizung einbaue. 
Meine Überlegung ist eher einfach. Ich möchte das Niveau der Heizkennlinie aktiv regulieren. Klang für mich nach einer guten Lösung, bei der ich nicht groß in die bestehende Regelung eingreifen muss.

Folgende Sensoren habe ich dafür in HA zur Verfügung:
- stündliche Wettervorhersage (Wind, Temperatur) über DWD
- stündliche Vorhersage der Sonneneinstrahlung über Forecast.Solar

Wenn beispielsweise morgens die gemessene Außentemperatur bei 0 Grad ist, gleichzeitig die Vorhersage mir sagt, dass es in 3 Stunden 8 Grad haben und es viel Sonne geben wird, könnte ich das Niveau der Heizkennlinie absenken und somit die Heizung frühzeitig herunterregeln. 
Andersherum könnte die Heizung früher hochregeln, wenn ein Kälteeinbruch oder auch Sturm erwartet wird. Meine Fußbodenheizung ist recht träge, da könnte das interessant sein.
Ich muss mich mal einlesen, ob das wirklich sinnvoll wäre und wie die Formel dazu aussehen könnte. 

Aktuell habe ich noch das Problem, dass der Home Assistant Sensor für das Außenthermometer bei "minus"-Temperaturen immer 50° C angezeigt. Hast Du das Problem bei Dir auch und ggf. gelöst?

Viele Grüße

**Reply by THorst92** [reply]
Hey @brixharlem,

die Anwendung klingt sehr spannend gerade für träge Heizsysteme wie die Fußbodenheizung! Da fällt mir ein, dass ich die nachgebaute Kennlinienfunktion in einem Forum gefunden habe, vielleicht brauchst du sie: https://www.haustechnikdialog.de/Forum/t/245522/Raumtemperatur-Sollwert-vs-Niveau-der-Heizkennlinie?page=4

Dein Problem klingt nach einem Datentypproblem. Die niedrigste gemessene Außentemperatur war bei mir 0.1 Grad, daher war noch nicht in dem Bereich. Ich werde das bei mir mal beobachten.

Viele Grüße

**Reply by Tom-Bom-badil** [reply]
Ja, an der Heizkennlinie wurde lange getüftelt, bis sie brauchbar war. Zum Glück hatte robhubi die notwendige Geduld. Hab sie auch hier ins Wiki aufgenommen - allerdings ziemlich versteckt [am Ende](https://github.com/Tom-Bom-badil/samson_trovis_557x/wiki/Begriffe-und-'Basics'#n%C3%A4herungsformel-f%C3%BCr-die-trovis-heizkennlinie-heizkurve).

/tom

**Reply by THorst92** [reply]
Oh den Eintrag hatte ich gar nicht gesehen. Vielen Dank für den Hinweis! ☺️

**Reply by Tom-Bom-badil** [reply]
Kein Problem. ;) Hab die Kennlinie gebraucht, da ich sie in meiner Visu darstellen wollte - hier mal ein aktueller Bildschirmausschnitt aus der Heizungsseite der Visu:

![image](https://github.com/Tom-Bom-badil/samson_trovis_557x/assets/20954551/2a96df09-b245-4349-919a-944d52fe3541)

Der Kurvenverlauf sieht wirklich gut aus und passt; Differenzen ergeben sich meist aufgrund von Einstellungen bei Adaption (COx-F08), Optimierung (COx-F07) sowie verzögerter Außentemperaturanpassung (CO5-F05+06).

Ich hab aber nie verstanden, warum der Sockelpunkt bei genau '24 + Niveau' liegen soll (Niveau ist klar, aber wieso 24 - der Nullpunkt liegt bei allen mir bekannten Trovis-Diagrammen bei AT20/VL20 - also wieso hier AT20/VL24)?

/tom

**Reply by brix29** [reply]
Sehr cool. Vielen Dank Euch beiden, @THorst92 @Tom-Bom-badil 
Ich werde es mit einer unkomplizierten Verschiebung des Niveaus mal testen und berichten.

@THorst92 Aktuell sind bei mir auch nur Plus-Grade... Wenn's kälter ist, werde ich mal in die Logfiles schauen. Es lässt sich hoffentlich leicht lösen.

**Reply by brix29** [reply]
Hi @THorst92,

solltest Du das Problem mit den Minuswerten der Außentemperatur auch haben, hier meine Lösung:

```
sensor:
  - platform: modbus_controller
    modbus_controller_id: trovis
    name: "Außentemperatur"
    id: AussentempAF1
    unit_of_measurement: "°C"
    icon: "mdi:home-thermometer"
    register_type: holding
    address: 9
    accuracy_decimals: 1
    filters:
      - lambda: |-
          if (x > 32767) {
              x = (x - 65536) * 0.1;
          } else {
              x = x * 0.1;
          }
          if (x < -50.0) {
              return -50.0;
          } else if (x > 50.0) {
              return 50.0;
          } else {
              return x;
          }
```

**Reply by THorst92** [reply]
Hi @brixharlem,

was mir noch gekommen ist, du könntest auch mal ausprobieren den Parameter
`value_type: S_WORD`
einzufügen (siehe [hier](https://esphome.io/components/sensor/modbus_controller.html)).

@Tom-Bom-badil: So eine Ansicht möchte ich mir auch noch bauen. Sieht super aus ☺️ 

Gruß

**Reply by brix29** [reply]
@THorst92 Deutlich eleganter. Hätte ich mich gar nicht so abmühen müssen. 😄

```
sensor:
  - platform: modbus_controller
    modbus_controller_id: trovis
    name: "Außentemperatur"
    id: AussentempAF1
    unit_of_measurement: "°C"
    icon: "mdi:home-thermometer"
    value_type: S_WORD
    register_type: holding
    address: 9
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
```

**Reply by Tom-Bom-badil** [reply]
@THorst92: Die Bilder sind in CorelDraw und Photoshop selbst gezeichnet - Du findest sie [in diesem Repo](https://github.com/Tom-Bom-badil/sv-simple-layout/tree/main/Rene) im pics/heizung Ordner. Den Digital-Font auf dem Display findest Du unter fonts/. CSS inkl. relative Positionierungen, Farben usw kannst Du aus der zugehörigen [HTML-Steuerdatei](https://github.com/Tom-Bom-badil/sv-simple-layout/blob/main/Rene/heizung.html) übernehmen.

/tom

**Reply by THorst92** [reply]
@brixharlem: Super dass es klappt, hab es bei mir auch gleich mit aufgenommen.
@Tom-Bom-badil: Danke für die Links. Werde es mir anschauen!

**Reply by brix29** [reply]
Falls es von Interesse sein sollte, die Aussteuerung über die DWD Wettervorhersage klappt sehr gut. Ich passe das Niveau der Heizkurve dynamisch an die Wettervorhersage an. Meine Annahme ist, dass meine Fußbodenheizung etwa 4 Stunden braucht, um auf eine Wetteränderung zu reagieren.
Daher nehme die Durchschnittstemperatur der Wettervorhersage in 4 bis 8 Stunden und berechne die Differenz zur Live Temperatur. 

`(Dynamisches) Niveau Heizkurze  = Niveau Normalwert + ((Temperaturdifferenz Live Temperatur - DWD Vorhersage) * Anpassungsfaktor)`

An Tagen, die nachts sehr kalt sind und tagsüber sehr warm, kann man sehen wie es funktioniert. Unten im Graphen seht ihr wie das Niveau angepasst wurde.
<img width="347" alt="image" src="https://github.com/Tom-Bom-badil/samson_trovis_557x/assets/76452633/d9572444-85a4-4726-9e30-3556b35775fb">


Hier noch die Home Assistant Sensoren. Automatisierungen liefere ich gerne nach, wenn Interesse besteht.  
```
input_number:
  normalwert_heizniveau:
    name: Normalwert Heizniveau
    min: -10
    max: 0
    step: 0.5
    unit_of_measurement: "°C"
    icon: mdi:thermostat

  anpassungsfaktor:
    name: Anpassungsfaktor
    min: 0
    max: 1
    step: 0.1
    icon: mdi:tune

sensor:
  - platform: template
    sensors:
      angepasstes_heizniveau:
        friendly_name: "Angepasstes Heizniveau nach DWD"
        unit_of_measurement: "°C"
        value_template: >
          {% set normalwert = states('input_number.normalwert_heizniveau') | float %}
          {% set temperaturdifferenz = states('sensor.temperaturdifferenz_aussen') | float(default=0) %}
          {% set anpassungsfaktor = states('input_number.anpassungsfaktor') | float(default=0) %}
          {% set angepasstes_niveau = normalwert + (temperaturdifferenz * anpassungsfaktor) %}
          {% set gerundet = (angepasstes_niveau * 2) | round() / 2 %}
          {{ gerundet }}
      temperaturdifferenz_aussen:
        friendly_name: "Temperaturdifferenz Außen zu DWD"
        unit_of_measurement: "°C"
        value_template: >
          {% set differenz = (states('sensor.oberhaching_laufzorn_temperatur_2') | float) - (states('sensor.dwd_temp_vorhersage_heizung') | float) %}
          {% set differenz_gerundet = (differenz * 2) | round() / 2 %}
          {{ differenz_gerundet }}
      dwd_temp_vorhersage_heizung:
        friendly_name: "DWD Durchschnittstemperatur in 4-8 Stunden"
        unit_of_measurement: "°C"
        value_template: >
          {% set data = state_attr('sensor.oberhaching_laufzorn_temperatur_2', 'data') %}
          {% set summe = data[5].value + data[6].value + data[7].value + data[8].value %}
          {{ (summe / 4) | round(2) }}

group:
  heizungssteuerung:
    name: Heizungssteuerung nach DWD
    entities:
      - input_number.normalwert_heizniveau
      - input_number.anpassungsfaktor
      - sensor.angepasstes_heizniveau
      - sensor.temperaturdifferenz_aussen
      - sensor.dwd_temp_vorhersage_heizung
```

**Comment by falkio8** [comment]
Ich habe schon lange meine 5573 per Modbus TCP Adaper im HA laufen. Lese bisher aber nur Werte. Ich würde gerne mal schreiben um z.B. die Heizung zu deaktivieren. Aber ich verstehe noch nicht wie ich das machen soll. Ich habe verstanden dass ich irgendwie auf

40145;  "5573"____________;  "ALG-MOD";      "Write-En_Modem"__;  "Modem-Schreibfreigabe (Schlüsselzahleingabe)"______;  0;   0,000;               1999,000;

Die Schlüsselzahl "eingeben" muss. Obwohl das bei mir im HA nur ein Schieberegler ist. Ich habe die config in modbus2mqtt eingelesen, damit ich die entities als Gerät zusammengefasst bekomme. Kann dort aber nicht den Typ einstellen von Verstellwerten.

<img width="475" height="237" alt="grafik" src="https://github.com/user-attachments/assets/4c22fd72-5ffa-45a5-82ee-59d7d58ff224" />

Wie muss ich vorgehen damit ich den per Schlüsselzahl "freischalte" und wie stelle ich dann andere Register/Coils ein?

**Reply by Tom-Bom-badil** [reply]
Warum dort auf Deinem Dashboard ein Slider ausgegeben wird, lässt sich aus der Ferne schwer sagen. Schau Dir mal genauer an, wie die Darstellung der Entitäten in der GUI (Lovelace) angelegt wurde. Schieberegler ist ja nur eine mögliche Form der Darstellung von Entitäten.

Schreibvorgänge werden in HA immer durch einen service call (hier: `modbus.write_register` bzw. `modbus.write_coil`) ausgelöst. Dafür brauchst Du den Slider nicht, sondern kannst das auch einfach auf einen Button oder einen Switch legen, z.B. ungefähr so:

```
type: button
name: Schreibmodus
show_icon: false
show_name: true
tap_action:
  action: call-service
  service: modbus.write_register
  service_data:
    hub: trovis
    unit: 247
    address: 144
    value: 1732
```

Es lassen sich auch mehrere Schreibvorgänge nacheinander ausführen; also zB erst Register der Schlüsselzahl beschreiben, gleich danach das Register mit der Funktion, die Du ändern willst. Hierzu mal in der die HA Doku / im HA Forum suchen, es gibt da reichlich Beispiele.

Viel Erfolg!

/tom
